"""AI-powered policy document parser for Entropy Compliance.

Extracts actionable compliance rules from uploaded PDF policy documents
using the configured LLM provider, then translates them into
Entropy-compatible guardrails YAML.
"""

from __future__ import annotations

import json
import re
import textwrap
from typing import Any

import structlog

logger = structlog.get_logger(__name__)

_SYSTEM_PROMPT = textwrap.dedent("""
    You are PolicyGuard, an enterprise-grade AI-powered Data Policy Compliance Agent.

    When given a policy document excerpt, extract ALL actionable compliance rules.
    For each rule output a JSON object with this exact schema:
    {
        "rule_id": "<REGULATION>-<sequence>",
        "regulation": "GDPR|HIPAA|CCPA|DPDP|SOC2|ISO27001",
        "category": "<category>",
        "description": "<plain English description>",
        "trigger_condition": "<when this rule is violated>",
        "severity": "CRITICAL|HIGH|MEDIUM|LOW"
    }

    Return ONLY a JSON array of these objects ΓÇö no markdown, no preamble.
    Supported regulations: GDPR, CCPA, HIPAA, DPDP Act 2023, SOC 2, ISO 27001.
""").strip()


def _rules_to_guardrails_yaml(rules: list[dict[str, Any]], source: str) -> str:
    """Convert extracted rules into entropy.yaml-compatible guardrail definitions."""
    lines = [
        f"# Auto-generated by Entropy Compliance from: {source}",
        "# Review before deploying to production.",
        "",
        "guardrails:",
    ]

    for rule in rules:
        sev = rule.get("severity", "MEDIUM").lower()
        action = "block" if sev in ("critical", "high") else "log"
        confidence_map = {"critical": 0.95, "high": 0.85, "medium": 0.70, "low": 0.55}
        confidence = confidence_map.get(sev, 0.70)

        lines += [
            f"  - name: {rule['rule_id']}",
            f"    description: \"{rule['description']}\"",
            f"    regulation: {rule.get('regulation', 'UNKNOWN')}",
            f"    category: \"{rule.get('category', 'General')}\"",
            f"    action: {action}",
            f"    confidence: {confidence}",
            f"    severity: {sev}",
            "",
        ]

    return "\n".join(lines)


class PolicyParser:
    """Parse uploaded policy PDF text into compliance rules + guardrails YAML."""

    def __init__(self, provider_registry: Any) -> None:
        self.registry = provider_registry

    async def extract_rules(
        self,
        document_text: str,
        source_filename: str,
        model: str = "gpt-4o-mini",
    ) -> list[dict[str, Any]]:
        """Send policy text to LLM and get structured compliance rules back.

        Args:
            document_text: Raw text extracted from the PDF.
            source_filename: Original filename (for audit trail).
            model: LLM model to use for extraction.

        Returns:
            List of rule dicts.
        """
        # Chunk large documents to stay within context limits
        chunks = _chunk_text(document_text, max_chars=12_000)
        all_rules: list[dict[str, Any]] = []

        for i, chunk in enumerate(chunks):
            logger.info(
                "Extracting rules from policy chunk",
                chunk=i + 1,
                total=len(chunks),
                source=source_filename,
            )
            try:
                provider = await self.registry.get_provider(model)
                response = await provider.chat_completion(
                    messages=[
                        {"role": "system", "content": _SYSTEM_PROMPT},
                        {
                            "role": "user",
                            "content": (
                                f"Extract compliance rules from this policy document "
                                f"(source: {source_filename}):\n\n{chunk}"
                            ),
                        },
                    ],
                    model=model,
                    temperature=0.0,
                    max_tokens=2048,
                )
                content = response["choices"][0]["message"]["content"].strip()

                # Robustly parse JSON even if the LLM wraps it in markdown
                json_match = re.search(r"\[.*\]", content, re.DOTALL)
                if json_match:
                    rules = json.loads(json_match.group())
                    # Stamp source document
                    for r in rules:
                        r["source_document"] = source_filename
                    all_rules.extend(rules)

            except Exception as exc:
                logger.error(
                    "Rule extraction failed for chunk",
                    chunk=i + 1,
                    error=str(exc),
                )

        # Deduplicate by rule_id
        seen: set[str] = set()
        unique_rules = []
        for rule in all_rules:
            rid = rule.get("rule_id", "")
            if rid not in seen:
                seen.add(rid)
                unique_rules.append(rule)

        logger.info(
            "Policy extraction complete",
            source=source_filename,
            rules_found=len(unique_rules),
        )
        return unique_rules

    async def generate_guardrails_yaml(
        self,
        document_text: str,
        source_filename: str,
        model: str = "gpt-4o-mini",
    ) -> tuple[list[dict[str, Any]], str]:
        """Extract rules and produce entropy.yaml guardrail definitions.

        Returns:
            (rules_list, yaml_string)
        """
        rules = await self.extract_rules(document_text, source_filename, model)
        yaml_output = _rules_to_guardrails_yaml(rules, source_filename)
        return rules, yaml_output


def _chunk_text(text: str, max_chars: int) -> list[str]:
    """Split text into chunks of at most `max_chars` characters at paragraph boundaries."""
    paragraphs = text.split("\n\n")
    chunks, current, current_len = [], [], 0
    for para in paragraphs:
        if current_len + len(para) > max_chars and current:
            chunks.append("\n\n".join(current))
            current, current_len = [], 0
        current.append(para)
        current_len += len(para)
    if current:
        chunks.append("\n\n".join(current))
    return chunks or [text]


__all__ = ["PolicyParser"]
